version: "3"

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  server:
    image: session-6-assignment-new:latest
    ports:
      - 9000:9000
    depends_on:
      - postgres
